#!/usr/bin/env python
import sys

class URLMirror:
	def __init__(self):
		self.mirrors = { "ftp://ftp.gnu.org/gnu":"ftp://ftp.twaren.net/Unix/GNU/gnu",
			     "http://ftp.gnu.org/gnu":"http://ftp.twaren.net/Unix/GNU/gnu",
			     "http://curl.haxx.se/download": "http://curl.mirror.anstey.ca",
				}
	def tr(self, inurl):
		for k,v in self.mirrors.iteritems():
			if inurl.startswith(k):
				if isinstance(v,str):
					return inurl.replace(k, v)
				else:
					return v(inurl)
		return inurl

def main():
	mirtr = URLMirror()
	for inurl in sys.argv[1:]:
		sys.stdout.write(mirtr.tr(inurl) + "\n")

if __name__ == "__main__":
	main()

